export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const HANDLE_CHANGE="HANDLE_CHANGE"

export const CLEAR_UPLOADS="CLEAR_UPLOADS"


export const CHANGE_PAGE="CHANGE_PAGE"


export const SUBMIT_PIN_SUCCESS="SUBMIT_POST_SUCCESS"
export const SUBMIT_PIN_ERROR="SUBMIT_POST_ERROR"


export const GET_ALL_PINS="GET_ALL_PINS"


export const DELETE_PIN="DELETE_PIN"

export const SINGLE_PIN="SINGLE_PIN"


export const GET_SINGLE_PIN_REVIEWS="GET_SINGLE_PIN_REVIEWS"

export const CREATE_REVIEW_SUCCESS="CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_ERROR="CREATE_REVIEW_ERROR"

export const CURRENT_USER_PINS="CURRENT_USER_PINS"

export const ALL_SAVED_PINS="ALL_SAVED_PINS"

export const CURRENT_USER_SAVEDPINS="CURRENT_USER_SAVEDPINS"

export const DELETE_IMAGE="DELETE_IMAGE"

